### ISSUE TITLE
Wrong class_eval for MiniMagick

### ISSUE THREAD

**Issue by niedfelj** [tehprofessor/newrelic-carrierwave#1]
Within the MiniMagick code you are doing an RMagick.class_eval, so there is nothing traced for MiniMagick.

**Comment by tehprofessor** [comment]
Thanks for the report!

Fixed with: https://github.com/tehprofessor/newrelic-carrierwave/commit/2b2f542962700b2a0e521f86fb62af236093193f

**Comment by niedfelj** [comment]
Thanks for the code!

**Comment by tehprofessor** [comment]
No problem :) Hopefully it works well for you, it has been for me.
